[

    {
       
        "books": [
            {
                "Id": "1",
                "Name": "A Dictionary of Architecture ",
                "Subcat": "1",
                "Desc": "Containing over 5,000 entries from Aalto to ziggurat, this is the most comprehensive and up-to-date dictionary of architecture in paperback. Beautifully illustrated and written in a clear and concise style, it is an invaluable work of reference for both students of architecture and the general reader, as well as professional architects. Covers all periods of Western architectural history, from ancient times to the present day Concise biographies of leading architects, from Brunelleschi and Imhotep to Le Corbusier and Richard Rogers Over 250 illustrations specially drawn for this volume",
                "Bublisher": "THE BOOK SHOP",
                "Edition": "2007",
                "Isbn": "89564636 ",
                "Page": "200",
                "Price": "500",
                 "Qty ": "15",
                 "Img": "upload_image\/ARC9.jpg"
            },
            {
                "Id": "2",
                "Name": "Elephant Kingdom : Sculptures from Indian Architecture ",
                "Subcat": "1",
                "Desc": "Elephants occupy a special place in the life and art of India. Since ancient times, they have been treasured and pampered as the ultimate beasts of burden, venerated as the vehicles of gods and kings and even worshipped in their own right. Their legendary attributes of strength, intelligence, nobility and longevity are eulogized in myth, epic and popular literature. In the figural and decorative arts, elephants provide an enduring fascination. Elephant Kingdom traces the myriad stories and symbolisms behind India's much-loved animal, through its depictions in architectural sculpture. At the heart of the study is a collection of over 60 colour photographs from a diversity of antique settings-many of them in remote parts of the subcontinent. At centuries-old temples, monasteries, forts and palaces, elephants flank ceremonial entrances, enrich columns and capitals, form balustrades to stairways or stand as enigmatic sentinels of vast courtyards. Some are legendary characters in tales of dreams and salvation; others enact scenes from a faithfully observed natural history. Some transport kings and heroes into battle and the hunt; others are celestial messengers of rain, fertility and good fortune. From monumental freestanding sculptures to finely-worked narrative friezes, the warmth and energy of these depictions bear testimony to the achievements of countless anonymous artisans. ",
                "Bublisher": "Vikramjit Ram",
                "Edition": "2006",
                "Isbn": "81-88204-6",
                "Page": "250",
                "Price": "1000",
                 "Qty ": "-24",
                 "Img": "upload_image\/ARC8.jpg"
            },
            {
                "Id": "3",
                "Name": "Close to Events-Works of Bikash Bhattacharjee",
                "Subcat": "2",
                "Desc": "Launching his creative career in the late ?50s, Bikash Bhattacharjee stood out among his contemporaries by making hard-edged chiseled realism the core appeal of his canvases when realism or naturalism of every shade was considered a retrograde trend. Bikash?s strengths were his exceptional technical mastery and his power to charge the tangible appearance of the surface with the reality of the depth beneath. He was admired not merely for the near-illusionist evocation of realistic details, but for the obvious or subtle distortions in his imagery as a key to their complex multi-layered meanings. His realistic idiom is fascinatingly robust and compulsive, laced with rich irony, strong-veined allegory and lush visual metaphors. His portrait-based images enact the artist?s own experience of our time with all its dark social and moral tones and textures. Close to Events: Works of Bikash Bhattacharjee deals with Bikash?s early life in an old North Calcutta locality, the urban social ambience that shaped his creative personality and explores why he chose to remain ?close to events? and free from the dominant trends in post-Independence Indian art. It also analyses the technical and stylistic development of art with detailed exposition of some of the themes and subjects in the major series of his paintings. ",
                "Bublisher": "Manasij Majumder",
                "Edition": "2008",
                "Isbn": "978818973",
                "Page": "250",
                "Price": "2000",
                 "Qty ": "-24",
                 "Img": "upload_image\/ART6.JPG"
            },
            {
                "Id": "4",
                "Name": "A Social History of Indian Architecture ",
                "Subcat": "1",
                "Desc": "Studies in Indian architecture have been confined to those exploring the building techniques of palaces, temples, and tombs. Little attention has traditionally been paid by scholars to the patterns and influences involved in the making of domestic residences, market places, inns, community halls, courts, and other 'lesser' buildings. The result is the emergence of a very partial picture of what constitutes architecture in India. This volume se eks to overcome this inadequacy by examining the geographical, historical, and functional aspects of architecture in India. Looking beyond the point of view of dynasties, periods or religions, the book traces the various social and historical developments in the field. Following a multi-disciplinary approach that emphasizes sociological aspects, the volume examines in detail, settlement patterns, the architecture of individual houses and chaityas, as also structural materials used for their construction, in addition to those of palaces, funerary monuments, temples, mosques, and monasteries. While examining the planning and design orientation of peoples and architectural techniques across India, the volume pays special attention to that of western India especially Gujarat and Rajasthan. The author also addresses rural and urban patterns of setlement and the linkages between the two. He explains regional and period-specific phenomena, while also quoting from ancient accounts of towns. These vary from the typical urban and rural houses to the Muslim aristocratic residences and Rajput palaces. Based on extensive fieldwork, the author also documents family histories, lifestyles and usage of space to provide a comprehensive social history of Indian architecture. Complemented by over eighty figures including photographs, plans, and detailed diagrams, this book will interest scholars of architecture, history, sociology, and the informed lay reader",
                "Bublisher": "V.S. Pramar ",
                "Edition": "2007",
                "Isbn": "87558769 ",
                "Page": "300",
                "Price": "1000",
                 "Qty ": "0",
                 "Img": "upload_image\/ARC10.jpg"
            },
            {
                "Id": "5",
                "Name": "YOGIS, DESTINY & THE WHEEL OF TIME ",
                "Subcat": "5",
                "Desc": "Contents: Dedication; Acknowledgements; About the author; Preface; Preface to the 2nd edition; 1. That great guru; 2. Profile of a guru's life; 3. Prabhu bejoy Krishna Goswami; 4. I meet my guru; 5. Awakened kundalini; 6. Astrological instruction; 7. Pre-destination: The negative side; 8. Rokadia Hanuman Baba; 9. My Jyotish guru-1; 10. My Jyotish guru-2; 11. Pre-destination & divine bliss; 12. Nagari Das Baba; 13. Ranga Avadhoot; 14. Religion of yogis; 15. Caution & warning; 16. Ecstasies spring from fire-1; 17. Ecstasies spring from fire-2; 18. Ecstasies spring from fire-3; 19. Ecstasies spring from fire-4; 20. Ecstasies spring from fire-5; 21. Ecstasies spring from fire-6; 22. The seers; 23. Astrology, when it is an illumination; 24. Memory glows; 25. Why astrology at all?; 26. Poetical guidance; 27. Bliss & confusion; Index.",
                "Bublisher": "K.N. Rao",
                "Edition": "2005",
                "Isbn": "2589697 ",
                "Page": "285",
                "Price": "300",
                 "Qty ": "-24",
                 "Img": "upload_image\/ASTRO1.jpg"
            },
            {
                "Id": "6",
                "Name": "You Deserve, We Conserve A Biotechnological Approach to Wild",
                "Subcat": "3",
                "Desc": "There is a tremendous wealth of mega-biodiversity in the world. But the very existence of this wealth is under threat due to habitat destruction, pushing animals towards inbreeding depression and thereby paving way for their extinction. This has made essential human intervention and assisted reproductive technologies. Thus, the issues of conservation of wildlife and biodiversity have become the need of the hour, especially in terms of policy making at the government level. You deserve, We Conserve: A Biotechnological Approach to Wildlife Conservation contains 16 articles by scientists engaged in research on the conservation of wildlife, role of reproductive technologies and modern approaches being followed in wildlife conservation. It also deals with various techniques used in field conditions such as chemical capture, molecular genetics, ultrasonography, cryopreservation, wildlife forensics, etc. The present book will be of special interest to professionals engaged in forest and environment related activities, particularly wildlife conservationists, students pursuing their career in veterinary discipline of wild animals and policy makers. It will also be useful for nature enthusiasts, who have an interest in wildlif",
                "Bublisher": "M W Pandit \/ S Shivaji",
                "Edition": "2006",
                "Isbn": "9788189866",
                "Page": "160",
                "Price": "659",
                 "Qty ": "-24",
                 "Img": "upload_image\/forest.jpg"
            },
            {
                "Id": "7",
                "Name": "Visual Basic 2005",
                "Subcat": "17",
                "Desc": "'VB connectivity'",
                "Bublisher": "Pearson",
                "Edition": "2009",
                "Isbn": "VB111",
                "Page": "350",
                "Price": "120",
                 "Qty ": "-24",
                 "Img": "upload_image\/comp8.jpg"
            },
            {
                "Id": "8",
                "Name": "Java & Xml",
                "Subcat": "17",
                "Desc": "'Complete Reference'",
                "Bublisher": "TATA Mcgerw Hill",
                "Edition": "2010",
                "Isbn": "JJ123",
                "Page": "1800",
                "Price": "500",
                 "Qty ": "-24",
                 "Img": "upload_image\/comp9.jpg"
            },
            {
                "Id": "9",
                "Name": "Microsoft Windows Powershell Step By Step",
                "Subcat": "29",
                "Desc": "'Learn Microsoft Windows PowerShell step by step with hands-on instruction from a leading Microsoft scripting trainer. This guide features self-paced labs, timesaving tips, and dozens of sample scripts",
                "Bublisher": "Wilson",
                "Edition": "2006",
                "Isbn": "9788120332",
                "Page": "755",
                "Price": "295",
                 "Qty ": "-24",
                 "Img": "upload_image\/comp6.jpg"
            },
            {
                "Id": "10",
                "Name": "C# Programming",
                "Subcat": "17",
                "Desc": "'C# is platform independent,includes namespace,garbage collection,automatic memory management",
                "Bublisher": "Pearson",
                "Edition": "1999",
                "Isbn": "c#abd",
                "Page": "450",
                "Price": "300",
                 "Qty ": "-24",
                 "Img": "upload_image\/1861004877.jpg"
            },
            {
                "Id": "11",
                "Name": "Java Server Programming",
                "Subcat": "17",
                "Desc": "'jsp uses  html tags and run on java platform'",
                "Bublisher": "BPB Prakashan",
                "Edition": "2000",
                "Isbn": "jsp123",
                "Page": "1800",
                "Price": "560",
                 "Qty ": "-24",
                 "Img": "upload_image\/1861004656.jpg"
            },
            {
                "Id": "12",
                "Name": "Programming with Perl",
                "Subcat": "17",
                "Desc": "Perl is programming langauge which is not comfortable to handle.",
                "Bublisher": "Wrox",
                "Edition": "1995",
                "Isbn": "perl123",
                "Page": "560",
                "Price": "450",
                 "Qty ": "-24",
                 "Img": "upload_image\/0596000278.jpg"
            },
            {
                "Id": "13",
                "Name": "HTML for world wide web",
                "Subcat": "19",
                "Desc": "html uses tags,it''s  not case sensitive,work with own html tagswhich must be enclosed.",
                "Bublisher": "Elizabeth",
                "Edition": "2005",
                "Isbn": "htmlabc12",
                "Page": "560",
                "Price": "400",
                 "Qty ": "-24",
                 "Img": "upload_image\/0201354934.jpg"
            },
            {
                "Id": "14",
                "Name": "ASP Server Pages 3.0",
                "Subcat": "17",
                "Desc": "Active server pages uses xml files ,it run on internet explorer or other browser..",
                "Bublisher": "Microsoft",
                "Edition": "1995",
                "Isbn": "asp123",
                "Page": "1150",
                "Price": "950",
                 "Qty ": "-24",
                 "Img": "upload_image\/1861003382.jpg"
            },
            {
                "Id": "15",
                "Name": "Perl and CGI",
                "Subcat": "17",
                "Desc": "CGI for graphics purpose",
                "Bublisher": "Pearson",
                "Edition": "1999",
                "Isbn": "pc2343",
                "Page": "450",
                "Price": "300",
                 "Qty ": "-24",
                 "Img": "upload_image\/020135358X.gif"
            },
            {
                "Id": "16",
                "Name": "A Biological Survey for the Nation",
                "Subcat": "27",
                "Desc": "The National Biological Survey will produce the map we need to avoid the\\r\\neconomic and environmental \"train wrecks\" we see scattered across the country.\\r\\nNBS will provide the scientific knowledge America needs to balance the\\r\\ncompatible goals of ecosystem protection and economic progress",
                "Bublisher": "National Research Council",
                "Edition": "1994",
                "Isbn": "0-309-5860",
                "Page": "224",
                "Price": "450",
                 "Qty ": "-24",
                 "Img": "upload_image\/biology.gif"
            },
            {
                "Id": "17",
                "Name": "Book of Tea",
                "Subcat": "23",
                "Desc": "The Philosophy of Tea is not mere aestheticism in the ordinary acceptance of the term, for it expresses conjointly with ethics and religion our whole point of view about man and nature. It is hygiene, for it enforces cleanliness.It represents the true spirit of Eastern democracy by making all its votaries aristocrats in taste. (from \"The Book of Tea\")",
                "Bublisher": "Kakuzo Okakura",
                "Edition": "2008",
                "Isbn": "tea1",
                "Page": "80",
                "Price": "100",
                 "Qty ": "-24",
                 "Img": "upload_image\/bookoftea.jpg"
            },
            {
                "Id": "18",
                "Name": "Coffee : Scrumptious Drinks",
                "Subcat": "23",
                "Desc": "Every day, millions search for The Perfect Cup of Coffee in caf s, diners, and kitchens around the world. Here, coffee guru Betty Rosbottom offers easy-to-follow recipes guaranteed to please \\r\\nanyone who takes delight in sampling, sipping, and serving exquisite coffee concoctions.",
                "Bublisher": "Chronicle Books",
                "Edition": "2007",
                "Isbn": "cofee1",
                "Page": "96",
                "Price": "100",
                 "Qty ": "-24",
                 "Img": "upload_image\/cofee.jpg"
            },
            {
                "Id": "19",
                "Name": "Stone Soup",
                "Subcat": "24",
                "Desc": "A hungry traveler tricks a little old lady into cooking him soup starting with a stone.",
                "Bublisher": "Marcia Brown",
                "Edition": "1970",
                "Isbn": "soup45",
                "Page": "120",
                "Price": "350",
                 "Qty ": "-24",
                 "Img": "upload_image\/stonesoup.jpg"
            },
            {
                "Id": "20",
                "Name": "Pasta Perfection",
                "Subcat": "22",
                "Desc": "This new series will help you get back into the kitchen and experience the fun of creating sensationalmouth-watering meals thought he simplicity of easy-to-read, step-by-step ...",
                "Bublisher": "Belina Jeffer",
                "Edition": "2004",
                "Isbn": "p12",
                "Page": "80",
                "Price": "100",
                 "Qty ": "-24",
                 "Img": "upload_image\/pasta1.jpg"
            },
            {
                "Id": "21",
                "Name": "Bhartiya Vynjano ka khajana",
                "Subcat": "25",
                "Desc": "Vyanjan made by Sanjeev kapoor,he makes very sweet and delicious dishes",
                "Bublisher": "Sanjeev Kapoor",
                "Edition": "2009",
                "Isbn": "vya12",
                "Page": "120",
                "Price": "350",
                 "Qty ": "-24",
                 "Img": "upload_image\/bhartiya.jpg"
            },
            {
                "Id": "22",
                "Name": "Descriptious du Cafeier",
                "Subcat": "23",
                "Desc": "millions search for The Perfect Cup of Coffee in caf s, diners, and kitchens around the world. Here, coffee guru Betty Rosbottom offers easy-to-follow recipes guaranteed to please anyone who takes delight in sampling, sipping, and serving exquisite coffee concoctions.",
                "Bublisher": "International resource institute",
                "Edition": "1996",
                "Isbn": "caffee2",
                "Page": "96",
                "Price": "100",
                 "Qty ": "-24",
                 "Img": "upload_image\/cofee2.jpg"
            },
            {
                "Id": "23",
                "Name": "Your Income-Tax 2010",
                "Subcat": "8",
                "Desc": "A guide to income tax returns provides information on the most recent tax legislation, tax-filing tips, advice on how to reduce tax liabilities, helpful financial advice, and sample tax forms, worksheets,",
                "Bublisher": "J K Lasser Institute",
                "Edition": "2009",
                "Isbn": "it-3433",
                "Page": "848",
                "Price": "1000",
                 "Qty ": "-24",
                 "Img": "upload_image\/tax1.jpg"
            },
            {
                "Id": "24",
                "Name": "Your Income-Tax Professional Edition",
                "Subcat": "8",
                "Desc": "Provides information about filing requirements, exemptions, income, deductions, tax credits, shelters, and tax law.",
                "Bublisher": "J K Lasser Institute",
                "Edition": "2009",
                "Isbn": "it-121",
                "Page": "1024",
                "Price": "120",
                 "Qty ": "-24",
                 "Img": "upload_image\/tax2.jpg"
            },
            {
                "Id": "25",
                "Name": "J K Lesser's Tax Savings in your Pocket",
                "Subcat": "8",
                "Desc": "*  Save more for your child education now!\r\n   * Increase your retirement savings\r\n   * New deductions, tax breaks, and planning tips",
                "Bublisher": "John Wiley and Sons",
                "Edition": "2002",
                "Isbn": "it-122",
                "Page": "212",
                "Price": "300",
                 "Qty ": "-24",
                 "Img": "upload_image\/tax3.jpg"
            },
            {
                "Id": "26",
                "Name": "On Liberty",
                "Subcat": "8",
                "Desc": "the liberal tradition, revered for his defense of liberal principles and expansive personal liberty.",
                "Bublisher": "Princeton University Press",
                "Edition": "2001",
                "Isbn": "li-11",
                "Page": "264",
                "Price": "300",
                 "Qty ": "-24",
                 "Img": "upload_image\/li1.jpg"
            },
            {
                "Id": "27",
                "Name": "On Liberty in Focus",
                "Subcat": "8",
                "Desc": "his book gathers together for the first time J.S. Mill''s On Liberty and a selection of importantessays by the eminent scholars Isaiah Berlin, Alan Ryan, John Rees C.L. Ten'",
                "Bublisher": "John Stuart Mill",
                "Edition": "2002",
                "Isbn": "li-22",
                "Page": "296",
                "Price": "350",
                 "Qty ": "-24",
                 "Img": "upload_image\/li2.jpg"
            },
            {
                "Id": "28",
                "Name": "Debugging Microsoft .NET 2.0 Applications",
                "Subcat": "17",
                "Desc": "Get hands-on instruction for using the tools in Microsoft Visual Studio? 2005 to debug, tune, and test applications. This guide features practical advice and code samples for developers at all levels from a leading authority on improving code. Traditionally, tools for performance tuning, testing applications, and debugging code have been expensive, hard to learn, and difficult to use. While previous versions of Microsoft Visual Studio? have included debuggers and other code-improvement tools, Visual Studio 2005 presents developers with robust and useful tools and processes to help ensure top-quality code. In this guide, an expert on improving code, John Robbins, steps back from the expert-level information that characterized his previous debugging books to present hands-on, practical advice for working developers on how to use the debugging, testing, and tuning features in Visual Studio 2005",
                "Bublisher": "John Robbins (Wintellect)",
                "Edition": "2006",
                "Isbn": "net-1",
                "Page": "464",
                "Price": "699",
                 "Qty ": "-24",
                 "Img": "upload_image\/comp2.jpg"
            },
            {
                "Id": "29",
                "Name": "The Mad, Mad World of Cricket",
                "Subcat": "4",
                "Desc": "The funny side of the gentleman?s game?captured by a master cartoonist In India cricket is more than a game; it is a national obsession. And with a World Cup always around the corner, there is no better way to prepare for the excitement of seeing the men in blue in action than with renowned cartoonist Sudhir Dar?s creations.",
                "Bublisher": "Sudhir Dar",
                "Edition": "2005",
                "Isbn": "0143101846",
                "Page": "96",
                "Price": "125",
                 "Qty ": "-24",
                 "Img": "upload_image\/c1.jpg"
            },
            {
                "Id": "30",
                "Name": "Dream Team India: The Best World Cup Squad Ever !",
                "Subcat": "4",
                "Desc": "Are you one of those who just knows India will win the match the moment the game starts? Do you drown yourself in cricket and cricket-related trivia every four years and dream of seeing India win the World Cup? If the answer is ?yes? to any of the above, here is the team that will bring home the Cup for you. ",
                "Bublisher": "Book shop",
                "Edition": "2007",
                "Isbn": "014333015",
                "Page": "147",
                "Price": "200",
                 "Qty ": "-24",
                 "Img": "upload_image\/c2.jpg"
            },
            {
                "Id": "31",
                "Name": "HOW TO PREPARE FOR QUANTITATIVE APTITUDE FOR CAT",
                "Subcat": "33",
                "Desc": "More than 3000 questions categorised into three levels of difficulty - LOD1, LOD2 and LOD3 * Notes emphasising relative importance of topics in the CAT, at appropriate places in the book * Short-cut methods to aid faster solutions to problems * Five practice CAT tests (actual CAT questions based on memory)",
                "Bublisher": "Arun Sharma",
                "Edition": "2006",
                "Isbn": "0070483493",
                "Page": "310",
                "Price": "325",
                 "Qty ": "-24",
                 "Img": "upload_image\/COMPETITIVE8.jpg"
            },
            {
                "Id": "32",
                "Name": "Physics",
                "Subcat": "26",
                "Desc": "Get all you need to know with Super Reviews! Each Super Review is packed with in-depth, student-friendly topic reviews that fully explain everything about the subject.",
                "Bublisher": "Unknown",
                "Edition": "1995",
                "Isbn": "08",
                "Page": "1000",
                "Price": "495",
                 "Qty ": "-24",
                 "Img": "upload_image\/p2.jpg"
            },
            {
                "Id": "33",
                "Name": "Thermal Physics",
                "Subcat": "26",
                "Desc": "The book presents a lucid and systematic exposition of the fundamental principles of Thermal Physics.",
                "Bublisher": "S.C.Garg",
                "Edition": "2001",
                "Isbn": "0074601342",
                "Page": "412",
                "Price": "163",
                 "Qty ": "-24",
                 "Img": "upload_image\/p6.jpg"
            },
            {
                "Id": "35",
                "Name": "A TEXTBOOK OF COST AND MANAGEMENT ACCOUNTING 8th ed.",
                "Subcat": "6",
                "Desc": " Student friendly and examination oriented approach # Innovative, comprehensive and systematic presentation of the subject matter # Use of diagrams and exhibits to help students understand concepts easily and clearly # Around 500 solved problems and illustrations with working notes # Solved and unsolved practical questions from various university and professional examinations like BCom, MCom, CA, CS, ICWA, etc. # Objective type questions and select theory questions # Ideal for self study.",
                "Bublisher": "M N ARORA",
                "Edition": "2006",
                "Isbn": "812910945",
                "Page": "400",
                "Price": "395",
                 "Qty ": "-24",
                 "Img": "upload_image\/busi7.jpg"
            },
            {
                "Id": "36",
                "Name": "Computer Networks, 4th Ed",
                "Subcat": "20",
                "Desc": "(38, 'Computer Networks, 4th Ed', '46', 'updated, this classic bestseller, now in its fourth edition, reflects the newest and most important networking technologies with a special emphasis on wireless networking. The material on wireless networks includes detailed coverage of 802.11, wireless local loops, 2G and 3G cellular networks, BluetoothTM, WAP, i-mode, and others. It prepares students to work with wireless technologies in networks of all sizes-both local and wide area networks. There is also lots of new material on applications, including the Web, Internet radio, voice over IP, and video on demand. Finally, an entirely new chapter is devoted exclusively to security to help students deal with one of the most crucial topics in networking today. Despite a large amount of material added on wireless networks, fixed networks have not been ignored-topics covered include ADLS, Internet over cable, gigabit Ethernet, peer-to-peer networks, NAT, and MPLS. Each chapter follows a consistent approach. The author first presents the key principles-underlying hardware at the physical layer up through the top-level application layer-and then illustrates them utilizing real-world examples drawn from the Internet and wireless networks, all in Tanenbaum''s classic entertaining style.",
                "Bublisher": "ANDREW S.TANENBAUM",
                "Edition": "2007",
                "Isbn": "8120321758",
                "Page": "912",
                "Price": "325",
                 "Qty ": "-24",
                 "Img": "upload_image\/comp7.jpg"
            },
            {
                "Id": "37",
                "Name": "Investing for Beginners",
                "Subcat": "6",
                "Desc": "Investment Risks and Rewards: How to overcome the fear of investment risk and how taking a few risks can reap long-term benefits. Your Starting Point: How to assess your investment goals. Diversification: How to allocate your money among various investment avenues for safety, steady income and capital growth. How to Pick Stocks: How to use fundamental indicators of value to pick good stocks. Investing in Bonds: Why you need bonds in your portfolio and which bonds to choose. Mutual Funds Primer: What they are and how to select the ones that suit your needs. Disinvesting: How to figure out when it''s time to get out of an investment. Keeping in Touch: How to understand financial information. Keeping Track of Your Investments: Simple record-keeping tricks.",
                "Bublisher": "Kathy Kristof",
                "Edition": "2006",
                "Isbn": "8170944821",
                "Page": "140",
                "Price": "195",
                 "Qty ": "-24",
                 "Img": "upload_image\/business.jpg"
            },
            {
                "Id": "38",
                "Name": "Games Lawyers need to Play - Moot Court Problems ",
                "Subcat": "8",
                "Desc": "The Raj Anand Moot Court Competition was initiated in 1998 with its focus centrally on Intellectual Property law. Over the years the scope of the Competition has widened though Intellectual Property remains the core area. One of its primary aims is to sharpen the skills of ?mooting? among aspiring lawyers. Games Lawyers Need to Play brings together the Problems and ten of the finest Memorials of the Competition. Each chapter deals with a specific year beginning with 2004 and going back to 1998. The problems deal with various aspects of Intellectual Property but are ?out of ordinary?, to enable participants to combine good quality research with creativity and originality. The book has a foreword by Judge Michael Fysh, QC, SC. The Introduction is written by Pravin Anand.",
                "Bublisher": "Raj Anand Moot Court Competition ",
                "Edition": "2006",
                "Isbn": "818028025X",
                "Page": "424",
                "Price": "595",
                 "Qty ": "-24",
                 "Img": "upload_image\/lawyer.jpg"
            },
            {
                "Id": "39",
                "Name": "An ABC of Indian Culture : A Personal Padayatra of Half a Ce",
                "Subcat": "2",
                "Desc": "An authentic interpretation of over 400 Indian concepts and practices derived from a personal exploration of India over a period of 50 years. Arranged alphabetically, these range from key traditional ones such as 'dharma' to more contemporary ones such as 'secularism' and 'democracy' to popular ones such as Indian films! 'Padayatra' is a journey on foot and each selected concept and practice is treated as a stepping-stone in a journey to understanding what India is all about. Descriptions are based on personal experience maturing over half a century, and written in cultural essays that present the essence of the Indian tradition. Malformations of the tradition are explained but without polemics. The book is a sensitive, cultured and sophisticated introduction to India for an intelligent and serious readership, and will be invaluable also as a handy reference text for libraries, cultural exchange agencies, business orientation courses especially for those anticipating an extended interaction with India, and the like.",
                "Bublisher": "Peggy Holroyde",
                "Edition": "2005",
                "Isbn": "818820417X",
                "Page": "480",
                "Price": "595",
                 "Qty ": "-24",
                 "Img": "upload_image\/cul1.jpg"
            },
            {
                "Id": "40",
                "Name": "HOW TO PREPARE FOR THE CAT, 2\/E ",
                "Subcat": "33",
                "Desc": "More than 3000 questions categorised into three levels of difficulty - LOD1, LOD2 and LOD3 * Notes emphasising relative importance of topics in the CAT, at appropriate places in the book * Short-cut methods to aid faster solutions to problems * Five practice CAT tests (actual CAT questions based on memory)",
                "Bublisher": "MUNEER, MUHAMED",
                "Edition": "2006",
                "Isbn": "0070528462",
                "Page": "380",
                "Price": "499",
                 "Qty ": "-24",
                 "Img": "upload_image\/CAT.jpg"
            },
            {
                "Id": "42",
                "Name": "STATISTICS FOR BUSINESS AND ECONOMICS",
                "Subcat": "7",
                "Desc": "This book covers various aspects of the field of statistics in 20 chapters, making each topic relevant and useful. A unique feature of this book is the inclusion of databases to be utilized by computers and software statistical packages. Contents - Introduction ? Statistical Terms and Concepts ? Data Collection ? Data Presentation ? Data Characteristics: Descriptive Measures ? Basic Concepts of Probability ? Probability Distribution ? Sampling Distribution ? Statistical Inference: Estimation ? Hypothesis Testing I ? Hypothesis Testing II ? Hypothesis Testing III ? Hypothesis Testing IV (Comparing Several Proportions Chi Square Test) ? Hypothesis Testing V(Comparing Several Population Means) One-Way Analysis of Variance (ANOVA) ? Regression and Correlation Analysis ? Multiple Regression ? Non-Parametric Statistics ? Time Series Analysis ? Statistical Decision Making ? Statistical Quality.",
                "Bublisher": "J S CHANDAN ",
                "Edition": "2007",
                "Isbn": "8125904182",
                "Page": "212",
                "Price": "372",
                 "Qty ": "-24",
                 "Img": "upload_image\/9062999.jpg"
            },
            {
                "Id": "44",
                "Name": "Insight Guide Iceland",
                "Subcat": "9",
                "Desc": "A travel series unlike any other, Insight Guides go beyond the sights and into reality.",
                "Bublisher": "Perrottet, Tony (Edt)",
                "Edition": "0887291767",
                "Isbn": "0887291767",
                "Page": "300",
                "Price": "935",
                 "Qty ": "-24",
                 "Img": "upload_image\/t2.jpg"
            },
            {
                "Id": "45",
                "Name": "SPIDER MAN",
                "Subcat": "16",
                "Desc": "second 100 issues as May Mayday Parker learns that she can't escape her great responsibilities! Featuring the original Hobgoblin, the Black Tarantula and more! Plus: the saga of Spider-Girl! Collects Amazing Spider-Girl #0-6. ",
                "Bublisher": "Marvel Comics ",
                "Edition": "2001",
                "Isbn": "0785123415",
                "Page": "160",
                "Price": "606",
                 "Qty ": "-24",
                 "Img": "upload_image\/comic1.jpg"
            },
            {
                "Id": "46",
                "Name": "The Missing ",
                "Subcat": "15",
                "Desc": "The woman missing for five years. The Crime Scene Investigator who finds her. And the serial killer who wants them both dead? When Boston CSI Darby McCormick finds a raving and emaciated woman hiding at the scene of a violent kidnap, she runs a DNA search to identify the Jane Doe. The result confirms that the woman was abducted five years earlier and has somehow managed to escape from the dungeon in which she?s been caged. With a teenage couple also missing and the Jane Doe seriously ill, the clock is ticking for Darby as she hunts for the dungeon before anyone else disappears or dies. And when the FBI takes over the investigation, it becomes clear that a sadistic serial killer has been on the prowl for decades ? and is poised to strike again at any moment. A killer with links to horrors that Darby has desperately tried to bury in her past?\r\n\r\n",
                "Bublisher": "Chris Mooning ",
                "Edition": "2006",
                "Isbn": "0141030852",
                "Page": "416",
                "Price": "240",
                 "Qty ": "-24",
                 "Img": "upload_image\/fic1.jpg"
            },
            {
                "Id": "47",
                "Name": "Bhagavata Purana ",
                "Subcat": "11",
                "Desc": "Even after he has composed the awesome Mahabharata, the Maharishi Vyasa finds no peace.",
                "Bublisher": "Ramesh Menon ",
                "Edition": "2004",
                "Isbn": "8129109956",
                "Page": "1500",
                "Price": "995",
                 "Qty ": "-24",
                 "Img": "upload_image\/re7.jpg"
            },
            {
                "Id": "48",
                "Name": "Bill and Dave: How Hewlett and Packard Built the World`s Gre",
                "Subcat": "12",
                "Desc": "This is not a history of the Hewlett-Packard Company, or a book of business theory, or a definitive biography of William Hewlett and David Packard. I have chosen to write this book this way because of the desperate need the business world has right now for an archetype of enlightened management, enduring quality, and perpetual innovation. It is not enough to simply tell the story of Hewlett, Packard and their company. What are needed are the why? and the how?? The most momentous first meeting in modern business history took place in the unlikely setting of a bench beside a football field, between two Stanford University students in pads and helmets. A few years later, in 1938, Bill Hewlett and Dave Packard were working in a small garage in Palo Alto, California, building their first product, an audio oscillator. It was the start not only of a legendary company but also of an entire way of life in Silicon Valley?and, ultimately, of our modern digital age. Acclaimed journalist Michael S. Malone is the first to get the full story, based on unlimited and exclusive access to corporate and private archives, along with hundreds of employee interviews. He draws on new material to show how some of the most influential products of our time were invented and how a culture of innovation led HP to unparalleled success for decades. Malone also shows what was really behind the groundbreaking management philosophy??the HP way??that put people ahead of products or profits. Bill and Dave, at its heart, is a character study of two amazing men who revealed their character in how they structured their business, in the men and women they hired, and, most of all, in the power they entrusted to even the lowliest HP employee. Their story is something of a miracle?one from which we can never stop learning.",
                "Bublisher": "Michael S. Malone ",
                "Edition": "2005",
                "Isbn": "0143102397",
                "Page": "345",
                "Price": "500",
                 "Qty ": "-24",
                 "Img": "upload_image\/MANAGEMENT2.jpg"
            },
            {
                "Id": "58",
                "Name": "yogendra",
                "Subcat": "36",
                "Desc": "fddsf",
                "Bublisher": "sfddfsdsf",
                "Edition": "1992",
                "Isbn": "123456789",
                "Page": "250",
                "Price": "200",
                 "Qty ": "0",
                 "Img": "upload_image\/C.jpg"
            },
            {
                "Id": "50",
                "Name": "Learning SQL on SQL Server 2005 : The Simplest Way",
                "Subcat": "18",
                "Desc": "Anyone who interacts with today?s modern databases needs to know SQL (Structured Query Language), the standard language for generating, manipulating, and retrieving database information. In recent years, the dramatic rise in the popularity of relational databases and multiuser databases has fueled a healthy demand for application devel?opers and others who can write SQL code efficiently and correctly. If you?re new to databases or need a SQL refresher, Learning SQL on SQL Server 2005 is an ideal step-by-step introduction to this database query tool, with everything you need for programming SQL using Microsoft?s SQL Server 2005?one of the most powerful and popular database engines used today. Plenty of books explain database theory. This guide lets you apply the theory as you learn SQL. You don?t need prior database knowledge, or even prior computer knowledge. Based on a popular university-level course designed by authors Sikha Saha Bagui and Richard Walsh Earp, Learning SQL on SQL Server 2005 starts with very simple SQL concepts, and slowly builds into more complex query development. Every topic, concept, and idea comes with examples of code and output, along with exercises to help you gain proficiency in SQL and SQL Server 2005. With this book, you?ll learn: * Beginning SQL commands, such as how and where to type an SQL query, and how to create, populate, alter, and delete tables * How to customize SQL Server 2005?s settings and about SQL Server 2005?s functions * About joins, a common database mechanism for combining tables * Query development, the use of views and other derived structures, and simple set operations * Subqueries, aggregate functions, and correlated subqueries, as well as indexes and constraints that can be added to tables in SQL Server 2005 Whether you?re a self-learner who has access to the new Microsoft database, working on SQL Server with access at your company, or a computer science student or MIS student, Learning SQL on SQL Server 2005 will get you up to speed on SQL in no time.\r\n\r\n",
                "Bublisher": "Sikha Saha Bagui, Richard Walsh Earp ",
                "Edition": "2005",
                "Isbn": "9788184040",
                "Page": "360",
                "Price": "350",
                 "Qty ": "-24",
                 "Img": "upload_image\/comp10.jpg"
            }
        ]
    }
]